# 公共配置文件
# @author <a href="https://github.com/li stellaris">程序员鱼皮</a>
# @from <a href="https:// stellaris.icu">编程导航知识星球</a>
server:
  port: 8123
  servlet:
    context-path: /api
stellarisapi:
  client:
    access-key:  stellaris
    secret-key: abcdefgh