server:
  port: 8090
spring:
  redis:
    database: 2
    port: 6379
  redisson:
    database: 2
    host: localhost
    port: 6379
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source,  stellaris
      routes:
        - id: api_route
          uri: https://zelinai.com/biz/v1/app/chat/sync
          predicates:
            - Path=/api/cs/**
#        - id: add_request_header_route
#          uri: http://localhost:8123
#          predicates:
#            - Path=/api/**
#          filters:
#            - AddRequestHeader= stellaris, swag
#            - AddRequestParameter=name, dog
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/fallback
#        - id:  stellaris-fallback
#          uri: https:// stellaris.icu
#          predicates:
#            - Path=/fallback
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

